"use client";

import Image from "next/image";
import { useEffect, useState } from "react";
import { contact, gallery, procedures, type Procedure, whatsappUrl } from "@/data/site";

const booking = whatsappUrl("Olá, Andreissa! Vi seu site e gostaria de consultar horários disponíveis para extensão de cílios.");

function Arrow() { return <span aria-hidden="true">↗</span>; }

function Header() {
  const [open, setOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  const links = [["Início", "#inicio"], ["Procedimentos", "#procedimentos"], ["Resultados", "#resultados"], ["Sobre", "#sobre"], ["Cuidados", "#cuidados"], ["Contato", "#contato"]];
  useEffect(() => { document.body.style.overflow = open ? "hidden" : ""; return () => { document.body.style.overflow = ""; }; }, [open]);
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 40); onScroll(); window.addEventListener("scroll", onScroll, { passive: true }); return () => window.removeEventListener("scroll", onScroll); }, []);
  return <header className={`header${scrolled ? " scrolled" : ""}`}><a className="brand" href="#inicio" aria-label="Andreissa - início"><b>ANDREISSA</b><small>LASH DESIGNER</small></a><nav className={open ? "nav open" : "nav"} aria-label="Navegação principal">{links.map(([label, href]) => <a key={href} href={href} onClick={() => setOpen(false)}>{label}</a>)}<a className="nav-book" href={booking} target="_blank">Agendar <Arrow /></a></nav><button className="menu" onClick={() => setOpen(!open)} aria-expanded={open} aria-label={open ? "Fechar menu" : "Abrir menu"}><i/><i/></button></header>;
}

function Hero() {
  return <section className="hero" id="inicio"><Image src="/images/andreissa-hero.jpg" alt="Andreissa Ferreira, Lash Designer" fill priority sizes="100vw" className="hero-img"/><div className="hero-shade"/><div className="hero-copy"><p className="eyebrow">Lash Designer · Barrinha/SP</p><h1><span>Seu olhar.</span><em>Sua identidade.</em></h1><p className="lede">Extensões personalizadas para valorizar seu olhar com naturalidade, elegância e técnica.</p><div className="actions"><a className="button light" href={booking} target="_blank">Agendar horário <Arrow /></a><a className="text-link" href="#procedimentos">Ver procedimentos <span>↓</span></a></div></div><p className="hero-side">ANDREISSA · LASH DESIGNER</p><a className="scroll" href="#manifesto" aria-label="Continuar para o conteúdo">Descobrir <span>↓</span></a></section>;
}

function Manifesto() { return <section className="manifesto section" id="manifesto" data-reveal><p className="eyebrow dark">Uma beleza que já é sua</p><h2>Não é apenas sobre cílios.<br/>É sobre se reconhecer <em>ainda mais bonita.</em></h2><div className="manifesto-words"><span>Naturalidade</span><span>Cuidado</span><span>Confiança</span></div></section>; }

function Procedures({ onOpen }: { onOpen: (p: Procedure) => void }) {
  const p = procedures[0];
  return <section className="procedures section" id="procedimentos"><div className="section-head" data-reveal><div><p className="eyebrow dark">Procedimentos</p><h2>Escolha seu <em>olhar</em></h2></div><p>Cada aplicação é pensada para harmonizar com seus traços, sua rotina e a intensidade que você deseja.</p></div><article className="procedure-card" data-reveal><div className="procedure-image"><Image src={p.image} alt="Resultado do Volume Brasileiro" fill sizes="(max-width: 760px) 100vw, 52vw"/></div><div className="procedure-content"><p className="eyebrow dark">{p.eyebrow}</p><h3>{p.name}</h3><p>{p.description}</p><dl><div><dt>Efeito</dt><dd>Definido e elegante</dd></div><div><dt>Intensidade</dt><dd>Média a marcante</dd></div><div><dt>Durabilidade</dt><dd>{p.duration}</dd></div><div><dt>Investimento</dt><dd>{p.price}</dd></div></dl><div className="card-actions"><button className="button dark" onClick={() => onOpen(p)}>Ver detalhes</button><a className="text-link dark-link" href={whatsappUrl(`Olá, Andreissa! Vi seu site e gostaria de saber mais sobre o ${p.name} e verificar horários disponíveis.`)} target="_blank">Quero agendar <Arrow /></a></div></div></article></section>;
}

function ProcedureModal({ procedure, onClose }: { procedure: Procedure | null; onClose: () => void }) {
  useEffect(() => { if (!procedure) return; const esc = (e: KeyboardEvent) => e.key === "Escape" && onClose(); document.addEventListener("keydown", esc); return () => document.removeEventListener("keydown", esc); }, [procedure, onClose]);
  if (!procedure) return null;
  return <div className="modal-backdrop" role="presentation" onMouseDown={e => e.target === e.currentTarget && onClose()}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><button className="close" onClick={onClose} aria-label="Fechar detalhes">×</button><p className="eyebrow dark">Procedimento</p><h2 id="modal-title">{procedure.name}</h2><p>{procedure.description}</p><p className="modal-indication"><b>Indicado para</b>{procedure.indicatedFor}</p><div className="ratings">{procedure.ratings.map(r => <div key={r.label}><span>{r.label}</span><span aria-label={`${r.value} de 5`}>{"●".repeat(r.value)}<i>{"●".repeat(5-r.value)}</i></span></div>)}</div><dl className="modal-meta"><div><dt>Durabilidade</dt><dd>{procedure.duration}</dd></div><div><dt>Investimento</dt><dd>{procedure.price}</dd></div></dl><a className="button dark full" target="_blank" href={whatsappUrl(`Olá, Andreissa! Vi seu site e gostaria de saber mais sobre o ${procedure.name} e verificar horários disponíveis.`)}>Quero esse procedimento <Arrow /></a><small>A durabilidade pode variar conforme o ciclo natural dos cílios e os cuidados da cliente.</small></section></div>;
}

function Gallery() {
  const [active, setActive] = useState<number | null>(null);
  useEffect(() => { const esc = (e: KeyboardEvent) => e.key === "Escape" && setActive(null); document.addEventListener("keydown", esc); return () => document.removeEventListener("keydown", esc); }, []);
  return <section className="gallery section" id="resultados"><div className="section-head invert" data-reveal><div><p className="eyebrow">Portfólio</p><h2>Resultados <em>reais</em></h2></div><p>Trabalhos e momentos reais da trajetória da Andreissa, preservados sem filtros que alterem o resultado.</p></div><div className="gallery-grid">{gallery.map((item, i) => <button key={item.src} className={`gallery-item g${i+1}`} onClick={() => setActive(i)} data-reveal><Image src={item.src} alt={item.alt} fill sizes="(max-width: 760px) 100vw, 50vw"/><span>Ver imagem <Arrow /></span></button>)}</div>{active !== null && <div className="lightbox" role="dialog" aria-modal="true" aria-label="Visualização da galeria" onClick={() => setActive(null)}><button onClick={() => setActive(null)} aria-label="Fechar imagem">×</button><Image src={gallery[active].src} alt={gallery[active].alt} fill sizes="100vw"/></div>}</section>;
}

function Quiz() {
  const questions = [
    { q: "Qual resultado você procura?", options: ["Muito natural", "Natural, mas perceptível", "Marcante", "Bem volumoso"] },
    { q: "Como você prefere seu olhar?", options: ["Delicado", "Definido", "Intenso"] },
    { q: "Você já realizou extensão de cílios?", options: ["Sim", "Não"] },
  ];
  const [step, setStep] = useState(0); const [answers, setAnswers] = useState<string[]>([]);
  const done = step === questions.length;
  const select = (value: string) => { setAnswers([...answers, value]); setStep(step + 1); };
  const reset = () => { setStep(0); setAnswers([]); };
  return <section className="quiz section"><div className="quiz-intro" data-reveal><p className="eyebrow dark">Consultoria rápida</p><h2>Qual estilo combina <em>com você?</em></h2><p>Em três escolhas, você entende melhor a intensidade que procura para conversar com a Andreissa.</p></div><div className="quiz-box" data-reveal>{!done ? <><div className="progress"><span>0{step+1}</span><i><b style={{ width: `${((step+1)/questions.length)*100}%` }}/></i><span>0{questions.length}</span></div><h3>{questions[step].q}</h3><div className="quiz-options">{questions[step].options.map(o => <button key={o} onClick={() => select(o)}>{o}<span>→</span></button>)}</div>{step > 0 && <button className="back" onClick={() => { setStep(step-1); setAnswers(answers.slice(0,-1)); }}>← Voltar</button>}</> : <div className="quiz-result"><p className="eyebrow dark">Seu direcionamento</p><h3>{answers[0]?.includes("natural") || answers[1] === "Delicado" ? "Leveza com definição" : "Presença com equilíbrio"}</h3><p>Seu perfil indica um olhar {answers[1]?.toLowerCase()}, com resultado {answers[0]?.toLowerCase()}. Como há uma técnica confirmada no catálogo, a Andreissa pode avaliar pessoalmente se o Volume Brasileiro atende ao efeito desejado.</p><a className="button dark full" target="_blank" href={whatsappUrl(`Olá, Andreissa! Fiz a consultoria no site. Procuro um resultado ${answers[0]?.toLowerCase()}, com olhar ${answers[1]?.toLowerCase()}. ${answers[2] === "Sim" ? "Já fiz" : "Ainda não fiz"} extensão de cílios. Pode me orientar?`)}>Conversar com a Andreissa <Arrow /></a><button className="back" onClick={reset}>Refazer consultoria</button></div>}</div></section>;
}

function About() { return <section className="about section" id="sobre"><div className="about-image" data-reveal><Image src="/images/andreissa-sobre.jpg" alt="Retrato de Andreissa Ferreira" fill sizes="(max-width: 760px) 100vw, 45vw"/></div><div className="about-copy" data-reveal><p className="eyebrow dark">Sobre a Andreissa</p><h2>Beleza está nos <em>detalhes.</em></h2><p>Sou Andreissa Ferreira, Lash Designer. Meu trabalho nasceu do desejo de transformar o amor pela beleza em profissão e proporcionar a cada cliente um momento de cuidado, autoestima e confiança.</p><p>Desde 29 de março de 2026, construo essa trajetória com dedicação e atenção a cada detalhe, buscando valorizar as características únicas de cada olhar.</p><blockquote>“Quero que cada mulher saia do meu espaço se sentindo ainda mais maravilhosa.”</blockquote></div></section>; }

function Care() { const items = [["01", "Orientação", "Siga as recomendações fornecidas pela profissional após o atendimento."], ["02", "Delicadeza", "Evite manipular excessivamente os fios ou esfregar a região dos olhos."], ["03", "Higienização", "Mantenha a higienização conforme a orientação recebida no atendimento."], ["04", "Manutenção", "Respeite o período indicado para avaliar a manutenção dos fios."]]; return <section className="care section" id="cuidados"><div className="section-head" data-reveal><div><p className="eyebrow dark">Pós-procedimento</p><h2>Cuide do seu <em>novo olhar</em></h2></div><p>Pequenos cuidados ajudam a preservar a beleza e a durabilidade do resultado.</p></div><div className="care-grid">{items.map(([n,t,d]) => <article key={n} data-reveal><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div><p className="care-note">As orientações podem variar conforme a técnica utilizada. Siga sempre as recomendações fornecidas durante o atendimento.</p></section>; }

function Instagram() { return <section className="instagram section"><div className="ig-copy" data-reveal><p className="eyebrow dark">Instagram</p><h2>Acompanhe meu <em>trabalho</em></h2><p>Resultados, bastidores e novidades direto no perfil da Andreissa.</p><a className="text-link dark-link" href={contact.instagram} target="_blank" rel="noreferrer">{contact.instagramLabel} <Arrow /></a></div><div className="ig-strip">{["/images/resultado-02.jpg", "/images/andreissa-atendimento.jpg", "/images/resultado-03.jpg"].map((src,i) => <a href={contact.instagram} target="_blank" rel="noreferrer" key={src} aria-label="Abrir Instagram da Andreissa"><Image src={src} alt="Trabalho da Andreissa" fill sizes="33vw"/><span>0{i+1}</span></a>)}</div></section>; }

function Contact() { return <section className="contact section" id="contato"><div className="contact-inner" data-reveal><p className="eyebrow">Agendamento</p><h2>Pronta para transformar <em>seu olhar?</em></h2><p>Escolha seu procedimento e fale diretamente com a Andreissa para consultar horários disponíveis.</p><a className="button light big" href={booking} target="_blank">Agendar pelo WhatsApp <Arrow /></a></div><div className="location"><span>Atendimento em</span><b>Barrinha/SP</b><a href={whatsappUrl("Olá, Andreissa! Gostaria de consultar a localização do atendimento em Barrinha/SP.")} target="_blank">Consultar localização <Arrow /></a></div></section>; }

function Footer() { return <footer><div className="footer-brand"><b>ANDREISSA</b><span>LASH DESIGNER</span></div><div><p>Barrinha/SP</p><a href={contact.instagram} target="_blank">Instagram <Arrow /></a><a href={booking} target="_blank">WhatsApp <Arrow /></a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Andreissa Lash Designer.</span><span>Desenvolvido por Leonardo Labs</span></div></footer>; }

function Reveals() { useEffect(() => { const els = document.querySelectorAll("[data-reveal]"); const io = new IntersectionObserver(e => e.forEach(x => x.isIntersecting && x.target.classList.add("revealed")), { threshold: .12 }); els.forEach(x => io.observe(x)); return () => io.disconnect(); }, []); return null; }

export default function Site() { const [modal, setModal] = useState<Procedure | null>(null); return <><Reveals/><Header/><main><Hero/><Manifesto/><Procedures onOpen={setModal}/><Gallery/><Quiz/><About/><Care/><Instagram/><Contact/></main><Footer/><a className="whatsapp" href={booking} target="_blank" aria-label="Agendar pelo WhatsApp"><svg viewBox="0 0 32 32" aria-hidden="true"><path d="M16 3a12.7 12.7 0 0 0-11 19l-1.5 6 6.2-1.5A12.8 12.8 0 1 0 16 3Zm0 22.9c-2 0-3.9-.6-5.6-1.6l-.4-.2-3.7.9 1-3.6-.3-.4A10.2 10.2 0 1 1 16 25.9Zm5.6-7.6c-.3-.2-1.8-.9-2.1-1-.3-.1-.5-.2-.7.2l-1 1.2c-.2.2-.4.2-.7.1-2-.8-3.4-1.8-4.6-4-.3-.5.3-.5.8-1.6.1-.2 0-.5 0-.7l-1-2.5c-.3-.7-.6-.6-.9-.6h-.7c-.3 0-.7.1-1 .5-1 1-.9 2.3-.2 3.9 1.4 3.2 4.7 6.1 8.4 7.1 1.6.5 3 .4 4.1.3 1.3-.2 2.8-1.2 3.2-2.4.4-1.1.4-2 .3-2.2-.2-.2-.5-.3-.9-.4Z"/></svg><span>Agendar pelo WhatsApp</span></a><ProcedureModal procedure={modal} onClose={() => setModal(null)}/></>; }
